# Dataset
input_directory: '/global/cscratch1/sd/danieltm/ExaTrkX/quark_gluon_tagging'
train_split: [80000, 10000, 10000]
train_batch_size: 100
signal_goal: 0.5

# Model hyperparameters
n_layers: 6
n_channels: 1024
layer_norm: True
batch_norm: True
hidden_activation: Tanh
dropout: 0.2

# Training hyperparameters
lr: 0.001
patience: 15
factor: 0.3
weight: 1
edge_cut: 0.5
max_epochs: 50