# Dataset
program: train.py
method: bayes
project: HP_Optimization
metric:
    name: auc.max
    goal: maximize
parameters:
    # Dataset information
    input_directory: 
        value: '/global/cscratch1/sd/danieltm/ExaTrkX/quark_gluon_tagging'
    train_split: 
        value: [80000, 10000, 10000]
    train_batch_size: 
        value: 100
    signal_goal: 
        value: 0.5

    # Model hyperparameters
    input_channels:
        min: 2
        max: 45
    n_layers: 
        min: 1
        max: 10
    n_channels: 
        min: 8
        max: 2048
    layer_norm: 
        values: [False, True]
    batch_norm: 
        values: [False, True]
    hidden_activation: 
        values: [ReLU, SiLU, Tanh]
    dropout: 
        min: 0.01
        max: 0.5

    # Training hyperparameters
    lr: 
        min: 0.00001
        max: 0.1
    patience: 
        min: 4
        max: 25
    factor: 
        min: 0.1
        max: 0.5
    weight: 
        value: 1
    edge_cut: 
        value: 0.5
    max_epochs: 
        value: 5